// ── Roadmap ─────────────────────────────────────────────────────────────
export type RoadmapLevel = "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ALL_LEVELS";
export type ResourceKind = "VIDEO" | "ARTICLE" | "DOCS" | "COURSE" | "BOOK" | "PROJECT" | "OTHER";
export type ExperienceLevel = "NEW" | "SOME" | "EXPERIENCED";
export type EnrollmentGoal = "JOB_READY" | "SIDE_PROJECT" | "SCHOOL" | "CURIOUS";
export type EnrollmentStatus = "ACTIVE" | "PAUSED" | "COMPLETED" | "ABANDONED";
export type RoadmapTopicStatus = "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "SKIPPED";
export type DayOfWeek = "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";

export interface RoadmapResource {
  id: number;
  topicId: number;
  kind: ResourceKind;
  title: string;
  url: string;
  source: string | null;
  isFree: boolean;
  orderIndex: number;
}

export interface RoadmapTopic {
  id: number;
  sectionId: number;
  slug: string;
  title: string;
  summary: string;
  contentMd: string;
  estimatedHours: number;
  difficulty: number;
  orderIndex: number;
  prerequisiteSlugs: string[];
  miniProject: string | null;
  selfCheck: string | null;
  resources: RoadmapResource[];
}

export interface RoadmapSection {
  id: number;
  roadmapId: number;
  slug: string;
  title: string;
  summary: string;
  orderIndex: number;
  aiRegeneratedAt: string | null;
  topics: RoadmapTopic[];
}

export interface Roadmap {
  id: number;
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  level: RoadmapLevel;
  estimatedHours: number;
  coverImage: string | null;
  ogImage: string | null;
  isPublished: boolean;
  isPremium: boolean;
  isAiGenerated: boolean;
  ownerUserId: number | null;
  topicCount: number;
  outcomes: string[];
  prerequisites: string[];
  faqs: { q: string; a: string }[];
  tags: string[];
  enrolledCount: number;
  sections: RoadmapSection[];
  createdAt: string;
  updatedAt: string;
}

export interface RoadmapListItem {
  id: number;
  slug: string;
  title: string;
  shortDescription: string;
  level: RoadmapLevel;
  estimatedHours: number;
  coverImage: string | null;
  ogImage: string | null;
  topicCount: number;
  enrolledCount: number;
  tags: string[];
  updatedAt: string;
  /** Present when the roadmap was AI-generated by the authenticated user */
  isAiGenerated?: boolean;
  /** Set for AI-generated roadmaps that are not publicly published */
  ownerUserId?: number | null;
  /** Creator name for community (publicly shared) roadmaps */
  creatorName?: string | null;
}

export interface WeeklyPlanWeek {
  week: number;
  startDate: string;
  endDate: string;
  topicSlugs: string[];
  totalHours: number;
}

export interface RoadmapTopicProgress {
  id: number;
  enrollmentId: number;
  topicId: number;
  status: RoadmapTopicStatus;
  bookmarked: boolean;
  notes: string | null;
  completedAt: string | null;
  updatedAt: string;
}

export interface RoadmapEnrollmentSummary {
  totalTopics: number;
  completedTopics: number;
  inProgressTopics: number;
  bookmarkedTopics: number;
  percentComplete: number;
  hoursDone: number;
  hoursTotal: number;
}

export type RoadmapTrackStatus = "AHEAD" | "ON_TRACK" | "BEHIND";

export interface RoadmapProgressTrendPoint {
  date: string;
  completed: number;
  cumulative: number;
}

export interface RoadmapEnrollmentAnalytics {
  enrollmentId: number;
  currentStreak: number;
  longestStreak: number;
  onTrackStatus: RoadmapTrackStatus;
  paceDeviation: number;
  expectedTopicsCompleted: number;
  actualTopicsCompleted: number;
  topicsCompletedThisWeek: number;
  weeklyTarget: number;
  estimatedCompletionDate: string;
  targetEndDate: string;
  progressTrend: RoadmapProgressTrendPoint[];
}

export interface RoadmapEnrollment {
  id: number;
  userId: number;
  roadmapId: number;
  shareToken: string;
  hoursPerWeek: number;
  preferredDays: DayOfWeek[];
  startDate: string;
  targetEndDate: string;
  experienceLevel: ExperienceLevel;
  goal: EnrollmentGoal;
  status: EnrollmentStatus;
  weeklyPlan: WeeklyPlanWeek[];
  pdfUrl: string | null;
  topicProgress: RoadmapTopicProgress[];
  roadmap: Roadmap;
  createdAt: string;
  updatedAt: string;
}

export interface RoadmapEnrollmentListItem {
  id: number;
  userId: number;
  roadmapId: number;
  hoursPerWeek: number;
  startDate: string;
  targetEndDate: string;
  status: EnrollmentStatus;
  topicProgress: RoadmapTopicProgress[];
  roadmap: {
    id: number;
    slug: string;
    title: string;
    shortDescription: string;
    coverImage: string | null;
    topicCount: number;
    estimatedHours: number;
    /** Populated once the server select includes these fields */
    level?: RoadmapLevel;
    tags?: string[];
    isAiGenerated?: boolean;
    ownerUserId?: number | null;
  };
  createdAt: string;
}

export interface EnrollInput {
  hoursPerWeek: number;
  preferredDays: DayOfWeek[];
  experienceLevel: ExperienceLevel;
  goal: EnrollmentGoal;
}

export interface StudyBuddyDetails {
  id: number;
  name: string;
  profilePic: string | null;
  college: string | null;
  experienceLevel: ExperienceLevel;
  percentComplete: number;
  completedTopics: number;
  currentStreak: number;
  matchedAt: string;
}

export interface StudyBuddyResponse {
  enabled: boolean;
  preferSameCollege: boolean;
  status: "NOT_OPTED_IN" | "SEARCHING" | "MATCHED";
  buddy: StudyBuddyDetails | null;
}
